### PR TITLE
"minutes" 

### PR DESCRIPTION
**Pull request by KingTino104**

### CODE REVIEW

**Comment by MythicalDoggo** [comment]
Yeah i had 1 coins per sec

**Comment by devnote-dev** [comment]
Closing this as it has a merge conflict and there are no plans to continue updating v1.

**Comment by KingTino104** [comment]
are you sure its v1?

**Comment by devnote-dev** [comment]
@KingTino104 Yes it is v2, my bad. There are no plans to continue maintaining either of them.

**Pull request closed without merging**
